# Generated by Django 4.2.7 on 2025-03-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='answer_file',
            field=models.FileField(help_text='PDF de la réponse étudiante', upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback détaillé', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.FloatField(blank=True, help_text='Note sur 20', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date de soumission'),
        ),
    ]
